# Fonts
font_family             JetBrainsMono NF Bold
bold_font               JetBrainsMono NF ExtraBold
italic_font             JetBrainsMono NF Italic
bold_italic_font        JetBrainsMono NF ExtraBold Italic
font_size               10

allow_remote_control yes

# Shell
shell /usr/bin/fish
shell_integration no-cursor

window_padding_width 25
close_on_child_death yes

cursor_shape_unfocused beam
cursor_blink_interval 0.5 ease-in-out

cursor_trail 1

enable_audio_bell no

#hide_window_decorations yes

confirm_os_window_close 0

# Appearance
selection_background    #81A1C1   
selection_foreground    #2E3440   

cursor                  #D8DEE9
cursor_text_color       #2E3440

# Transparency
background_opacity      1

# Primary Colors
background              #303030
foreground              #BBBBBB

# Normal Colors
color0                  #3B4252
color1                  #BF616A
color2                  #A3BE8C
color3                  #D4AF7F
color4                  #81A1C1
color5                  #B48EAD
color6                  #88C0D0
color7                  #E5E9F0

# Bright Colors
color8                  #4C566A
color9                  #BF616A
color10                 #A3BE8C
color11                 #D4AF7F
color12                 #81A1C1
color13                 #B48EAD
color14                 #8FBCBB
color15                 #ECEFF4

# UI Tweaks
window_padding_width    10

url_color               #88C0D0

active_border_color     #303030
inactive_border_color   #4C566A
bell_border_color       #BF616A

active_tab_foreground   #FFFFFF
active_tab_background   #D4AF7F
inactive_tab_foreground #D8DEE9
inactive_tab_background #363131
tab_bar_background      #303030

# Optional: Marks
mark1_foreground        #2E3440
mark1_background        #81A1C1
mark2_foreground        #2E3440
mark2_background        #B48EAD
mark3_foreground        #2E3440
mark3_background        #8FBCBB   

