# Fonts
font_family             JetBrainsMono NF Bold
bold_font               JetBrainsMono NF ExtraBold
italic_font             JetBrainsMono NF Italic
bold_italic_font        JetBrainsMono NF ExtraBold Italic
font_size               10

# --- Prefix/leader style navigation (no modes)

# Choose a leader. ctrl+space sometimes gets eaten by IME / desktop stuff,
# so ctrl+g is a safer default. Use whatever you like.
# Here I'll use ctrl+g as leader:

map ctrl+g>h neighboring_window left
map ctrl+g>j neighboring_window down
map ctrl+g>k neighboring_window up
map ctrl+g>l neighboring_window right

map ctrl+g>H resize_window narrower 5
map ctrl+g>L resize_window wider 5
map ctrl+g>J resize_window taller 2
map ctrl+g>K resize_window shorter 2

map ctrl+g>t new_tab
map ctrl+g>x close_tab
map ctrl+g>n next_tab
map ctrl+g>p previous_tab

allow_remote_control yes

# Shell
shell /usr/bin/fish
shell_integration no-cursor

window_padding_width 25
close_on_child_death yes

cursor_shape_unfocused beam
cursor_blink_interval 0.5 ease-in-out

cursor_trail 1

enable_audio_bell no

#hide_window_decorations yes

confirm_os_window_close 0

# Appearance
selection_background    #91A1B1   
selection_foreground    #373737   

cursor                  #AAAAAA
cursor_text_color       #373737

# Transparency
background_opacity      1

# Primary Colors
background              #292828
foreground              #BBBBBB

# Normal Colors
color0                  #464646
color1                  #AC7479
color2                  #A4AE9B
color3                  #C6AD8D
color4                  #91A1B1
color5                  #505050
color6                  #96B8C2
color7                  #AAAAAA

# Bright Colors
color8                  #5B5B5B
color9                  #AC7479
color10                 #A4AE9B
color11                 #C6AD8D
color12                 #91A1B1
color13                 #A49EA3
color14                 #9EADAD
color15                 #AAAAAA

# UI Tweaks
window_padding_width    10

url_color               #96B8C2

active_border_color     #303030
inactive_border_color   #5B5B5B
bell_border_color       #AC7479

active_tab_foreground   #303030
active_tab_background   #617679
inactive_tab_foreground #DDDDDD
inactive_tab_background #343434
tab_bar_background      #303030

# Optional: Marks
mark1_foreground        #373737
mark1_background        #91A1B1
mark2_foreground        #373737
mark2_background        #A49EA3
mark3_foreground        #373737
mark3_background        #9EADAD   
