# Fonts
font_family      JetBrainsMono NF Bold
bold_font        JetBrainsMono NF ExtraBold
italic_font      JetBrainsMono NF Italic
bold_italic_font JetBrainsMono NF ExtraBold Italic
font_size 10

# Key mappings
map ctrl+g>h neighboring_window left
map ctrl+g>j neighboring_window down
map ctrl+g>k neighboring_window up
map ctrl+g>l neighboring_window right

map ctrl+g>H resize_window narrower 5
map ctrl+g>L resize_window wider 5
map ctrl+g>J resize_window taller 2
map ctrl+g>K resize_window shorter 2

map ctrl+g>t new_tab
map ctrl+g>x close_tab
map ctrl+g>n next_tab
map ctrl+g>p previous_tab

# Terminal behavior
allow_remote_control yes

shell /usr/bin/fish
shell_integration no-cursor

window_padding_width 10
close_on_child_death yes

cursor_shape_unfocused beam
cursor_blink_interval 0.5 ease-in-out
cursor_trail 1

enable_audio_bell no
confirm_os_window_close 0
background_opacity 1

# Active theme
include themes/gruvfjord.conf
