# Format:
# app_name=path1|path2|path3

# Browsers
#zen=$HOME/.zen/
#librewolf=$HOME/.config/librewolf
#thorium=$HOME/.config/thorium

# File managers / terminals / shells / editors
kitty=$HOME/.config/kitty
nemo=$HOME/.config/nemo
thunar=$HOME/.config/Thunar
ranger=$HOME/.config/ranger
fish=$HOME/.config/fish|$HOME/.local/share/fish
zsh=$HOME/.zshrc|$HOME/.oh-my-zsh
nvim=$HOME/.config/nvim|$HOME/.local/share/nvim

# Input / desktop UI
fcitx=$HOME/.config/fcitx
fcitx5=$HOME/.config/fcitx5
dunst=$HOME/.config/dunst
rofi=$HOME/.config/rofi
picom=$HOME/.config/picom
redshift=$HOME/.config/redshift
flameshot=$HOME/.config/flameshot
xsettingsd=$HOME/.config/xsettingsd
gtk=$HOME/.config/gtk-2.0|$HOME/.config/gtk-3.0|$HOME/.config/gtk-4.0
xfce4=$HOME/.config/xfce4
nwg-look=$HOME/.config/nwg-look
session=$HOME/.config/session

# TUI tools
btop=$HOME/.config/btop
fastfetch=$HOME/.config/fastfetch

# Audio / media / creative
mpd=$HOME/.config/mpd
rmpc=$HOME/.config/rmpc
mpv=$HOME/.config/mpv
ardour9=$HOME/.config/ardour9
renoise=$HOME/.config/Renoise
godot=$HOME/.config/godot
qalculate=$HOME/.config/qalculate
obsidian=$HOME/.config/obsidian

# Communication / desktop apps
#discord=$HOME/.config/discord
#vesktop=$HOME/.config/vesktop
stretchly=$HOME/.config/Stretchly

# IDEs / source control
vscodium=$HOME/.config/VSCodium|$HOME/.vscode-oss
