# Format:
# app_name=path1|path2|path3

# Browser

# File managers / terminals
kitty=$HOME/.config/kitty
nemo=$HOME/.config/nemo
thunar=$HOME/.config/thunar

# Language Switcher
fcitx=$HOME/.config/fcitx/
fcitx5=$HOME/.config/fcitx5/

# Compositor / display
picom=$HOME/.config/picom
redshift=$HOME/.config/redshift
dunst=$HOME/.config/dunst
rofi=$HOME/.config/rofi

# Shells / editors
fish=$HOME/.config/fish|$HOME/.local/share/fish
zsh=$HOME/.zshrc|$HOME/.oh-my-zsh

nvim=$HOME/.config/nvim|$HOME/.local/share/nvim

# TUI Tools
btop=$HOME/.config/btop
fastfetch=$HOME/.config/fastfetch/

# Audio / engines
mpd=$HOME/.config/mpd
rmpc=$HOME/.config/rmpc
ardour9=$HOME/.config/ardour9
Renoise=$HOME/.config/Renoise/
godot=$HOME/.config/godot

# IDEs
#vscodium=$HOME/.config/VSCodium|$HOME/.vscode-oss|$HOME/.local/share/VSCodium|$HOME/.cache/VSCodium

# Optional
git=$HOME/.gitconfig



