# Selection colors
selection_background #456978
selection_foreground #F1F6F8

# Cursor colors
cursor #D88C3A
cursor_text_color #11161A

# Base colors
foreground #B8B7AA
background #292828

color0  #2B3136
color1  #B76C43
color2  #4F855C
color3  #C08C3C
color4  #3C6F98
color5  #4A6792
color6  #2F848E
color7  #B8B7AA

color8  #4A5157
color9  #D28652
color10 #69A06E
color11 #D6A048
color12 #4F85B4
color13 #6482AE
color14 #45A1A8
color15 #D1CCBE

url_color #4CA7B2

# Border colors
active_border_color #3A7A87
inactive_border_color #394046
bell_border_color #C7773C

# Tab bar colors
active_tab_foreground #E0D9CA
active_tab_background #365E69
inactive_tab_foreground #A9A99B
inactive_tab_background #24292D
tab_bar_background #1C2124
