# Gruvfjord
# A Nordic x Gruvbox blend: cool fjord backgrounds with warm, earthy accents.

# Selection colors
selection_background #5C7799
selection_foreground #E9E4D3

# Cursor colors
cursor #D8B164
cursor_text_color #30353E

# Base colors
foreground #D8D1BD
background #292828

color0  #30353E
color1  #B1636B
color2  #5e6c69
color3  #D0AE66
color4  #7E99A8
color5  #AF90A9
color6  #84B0AD
color7  #D8D1BD

color8  #505766
color9  #C87075
color10  #5e6c69
color11 #E0BD77
color12 #8EA9B7
color13 #BAA0B0
color14 #95C0BD
color15 #E9E4D3

url_color #7DB1C0

# Border colors
active_border_color #7E99A8
inactive_border_color #464D5B
bell_border_color #BF7C68

# Tab bar colors
active_tab_foreground #E9E4D3
active_tab_background #4C6179
inactive_tab_foreground #B2AC9B
inactive_tab_background #3E434F
tab_bar_background #292828
